import { z } from "zod";
import { isValidEmail, isValidName, isValidPhone } from "./validation";

/**
 * Wire format shared by public/tracker.js and /api/track.
 * Everything here arrives from an untrusted browser, so every field is
 * validated and length-capped before it reaches the database.
 */

const shortString = z.string().trim().min(1).max(120);

// Client-generated ids. Constrained so they cannot be used to smuggle payloads.
const idString = z
  .string()
  .trim()
  .min(8)
  .max(64)
  .regex(/^[A-Za-z0-9_-]+$/, "invalid id");

const pathString = z.string().trim().max(300).optional();

export const INTERACTION_TYPES = ["click", "hover", "scroll", "pageview"] as const;

/** A single acquisition tag. Nullable because the client sends explicit nulls. */
const tag = z.string().trim().max(200).nullish();

/**
 * Acquisition params captured on the landing URL, once per session.
 *
 * The named fields are the ones we filter and group by in SQL; `rawParams` is
 * the catch-all so a new ad platform or a custom param is never lost. Bounded
 * on every axis — this arrives from an untrusted browser.
 */
export const entryMetaSchema = z.object({
  entryPath: z.string().trim().max(300).nullish(),
  referrer: z.string().trim().max(600).nullish(),
  utmSource: tag,
  utmMedium: tag,
  utmCampaign: tag,
  utmContent: tag,
  utmTerm: tag,
  gclid: tag,
  fbclid: tag,
  msclkid: tag,
  placement: tag,
  metaCampaignId: tag,
  metaAdsetId: tag,
  metaAdId: tag,
  rawParams: z
    .record(z.string().max(100), z.string().max(500))
    // A landing URL with 50 distinct params is an attack, not a campaign.
    .refine((value) => Object.keys(value).length <= 50, {
      message: "too many params",
    })
    .optional(),
});

export type EntryMeta = z.infer<typeof entryMetaSchema>;

export const sessionStartSchema = z.object({
  kind: z.literal("session"),
  clientId: idString,
  visitorId: idString,
  isReturning: z.boolean(),
  device: z.enum(["mobile", "tablet", "desktop"]),
  source: shortString.optional(),
  medium: shortString.optional(),
  campaign: shortString.optional(),
  path: pathString,
  // Optional so an older cached tracker.js keeps working after deploy.
  entryMeta: entryMetaSchema.optional(),
});

export const eventBatchSchema = z.object({
  kind: z.literal("events"),
  clientId: idString,
  events: z
    .array(
      z.object({
        type: z.enum(INTERACTION_TYPES),
        // Normalised page coordinates; anything outside 0-1 is a bug or a forgery.
        xPct: z.number().min(0).max(1).optional(),
        yPct: z.number().min(0).max(1).optional(),
        path: pathString,
      }),
    )
    .min(1)
    .max(50),
});

export const heartbeatSchema = z.object({
  kind: z.literal("heartbeat"),
  clientId: idString,
  scrollDepth: z.number().int().min(0).max(100),
});

export const trackPayloadSchema = z.discriminatedUnion("kind", [
  sessionStartSchema,
  eventBatchSchema,
  heartbeatSchema,
]);

export type TrackPayload = z.infer<typeof trackPayloadSchema>;

export const leadPayloadSchema = z.object({
  clientId: idString.optional(),
  // Same helpers the form uses, so the two boundaries cannot drift apart. This
  // is the one that matters: DevTools or a plain curl skips every client check.
  name: z.string().trim().max(120).refine(isValidName, "invalid name"),
  phone: z
    .string()
    .trim()
    .max(20)
    .refine(isValidPhone, "invalid phone")
    // Store digits only — the tel: link and Meta's phone hashing both want a
    // bare number.
    .transform((value) => value.replace(/\D/g, "")),
  email: z
    .string()
    .trim()
    .max(200)
    .refine(isValidEmail, "invalid email")
    .optional()
    .or(z.literal("")),
  budgetRange: shortString.optional(),
  configuration: shortString.optional(),
  /// Generated by the browser and passed to both the Pixel and the Conversions
  /// API so Meta deduplicates the two deliveries of the same conversion.
  eventId: z.string().trim().min(8).max(64).regex(/^[A-Za-z0-9_-]+$/).optional(),
});

export type LeadPayload = z.infer<typeof leadPayloadSchema>;

/**
 * Optional details added on the thank-you page, PATCHed onto the lead the
 * short landing-page form already created.
 */
export const leadEnrichSchema = z.object({
  // A cuid from the POST response — unguessable, so it doubles as the token
  // that authorises the update.
  leadId: z.string().trim().min(20).max(40).regex(/^[a-z0-9]+$/, "invalid id"),
  // Optional, so an empty string is allowed — but anything non-empty must be a
  // real address, checked with the same helper the thank-you form uses.
  email: z
    .string()
    .trim()
    .max(200)
    .refine(isValidEmail, "invalid email")
    .optional()
    .or(z.literal("")),
  budgetRange: shortString.optional().or(z.literal("")),
  configuration: shortString.optional().or(z.literal("")),
  message: z.string().trim().max(2000).optional().or(z.literal("")),
});

export type LeadEnrichPayload = z.infer<typeof leadEnrichSchema>;

/**
 * How long after submission a lead stays open to enrichment. The id travels in
 * a URL, so it can leak through history, referrers or a shared link — this
 * stops an old link being used to rewrite a lead indefinitely.
 */
export const ENRICH_WINDOW_MS = 24 * 60 * 60 * 1000;

/**
 * A batch of rrweb DOM-recording events for full session replay. The events
 * themselves are opaque rrweb objects, validated only for shape and count —
 * their internal structure is rrweb's concern, not ours.
 */
export const replayPayloadSchema = z.object({
  clientId: idString,
  seq: z.number().int().min(0),
  // Cap generously: the first batch carries rrweb's full DOM snapshot plus the
  // burst of hydration mutations, which can be large. Rejecting it would lose
  // the snapshot and leave an unplayable recording.
  events: z
    .array(z.object({ type: z.number(), timestamp: z.number() }).passthrough())
    .min(1)
    .max(5000),
});

export type ReplayPayload = z.infer<typeof replayPayloadSchema>;

/**
 * Bounce is derived server-side rather than trusted from the client.
 * A visit bounces when it shows no evidence of engagement: no meaningful
 * interaction, a short stay, and barely any scrolling.
 */
export function deriveBounced(input: {
  interactionCount: number;
  durationSec: number;
  scrollDepth: number;
  formFilled: boolean;
}): boolean {
  if (input.formFilled) return false;
  return (
    input.interactionCount <= 1 &&
    input.durationSec < 10 &&
    input.scrollDepth < 25
  );
}
